"""
sites/ti/register.py — Registers the-internet's actions.

Generated by /generate-poms from a crawl of the-internet.herokuapp.com, then
brought up to the current conventions. Imports are inside the function on
purpose: register_all_sites imports every site's register.py at startup, and a
module-level poms import here would pull the POM layer — and Playwright with
it — into runs that never touch a browser.
"""
from __future__ import annotations

def register(registry, screenshots_dir=None) -> None:
    from stepper.sites.ti.pages.login_action import TiLoginPage
    from stepper.sites.ti.pages.secure_action import TiSecurePage
    from stepper.sites.ti.pages.logout_action import TiLogoutPage
    from stepper.sites.ti.pages.checkboxes_action import TiCheckboxesPage
    from stepper.sites.ti.pages.dropdown_action import TiDropdownPage
    from stepper.sites.ti.pages.windows_action import TiWindowsPage
    from stepper.sites.ti.pages.js_alerts_action import TiJsAlertsPage
    from stepper.sites.ti.pages.hovers_action import TiHoversPage
    from stepper.sites.ti.pages.drag_and_drop_action import TiDragAndDropPage

    TiLoginPage.register(registry)
    TiSecurePage.register(registry)
    TiLogoutPage.register(registry)
    TiCheckboxesPage.register(registry)
    TiDropdownPage.register(registry)
    TiWindowsPage.register(registry)
    TiJsAlertsPage.register(registry)
    TiHoversPage.register(registry)
    TiDragAndDropPage.register(registry)
